graph TD;
    subgraph React
        LaunchProjectReadyReact[Ready]
        LaunchProjectReadyReact[Ready] --> CreateInertiaFileReact[CreateInertiaFile]
        CreateInertiaFileReact --> ReactURL[URL]
        CreateInertiaFileReact --> ReactTitle[Title]
    end

    subgraph SwiftUI
        LaunchProjectReady[Ready]
        InstallXcode[Install Xcode]
        XCodeProjectURL[XCode Project URL]
        EntryStructName[Entry Struct Name]
        SwiftUITitle[Title]
        LaunchProjectReady --> CreateInertiaFile[CreateInertiaFile]
        CreateInertiaFile[CreateInertiaFile] --> CompilingSwiftCodebase[Compiling Codebase]
        
        CompilingSwiftCodebase --> MutateSwiftCodebase[Mutate Codebase]
        MutateSwiftCodebase --> CopySwiftCodebase[Copy Codebase]
        CopySwiftCodebase --> InstallXcode
        CopySwiftCodebase --> XCodeProjectURL
        CopySwiftCodebase --> EntryStructName
        CopySwiftCodebase --> SwiftUITitle
    end