---
config:
  theme: dark
---
gantt
    title Inertia Graphics Roadmap
    dateFormat  YYYY-MM-DD
    section Proof of Concept (POC)
        Preprocessor           : active, a1, 2024-07-08, 2024-12-31
        Runtime                : active, a2, 2024-07-15, 2024-12-01
        Native Animations      : active, a3, 2024-08-08, 2024-10-01
        Layers of SwiftUI & Metal injected : active, a4, 2024-08-08, 2024-10-01
    section Prototype
        Animation Editor       : b1, 2025-01-01, 2025-02-01
        Timeline Editor       : b2, 2025-01-01, 2025-02-01
        Vector Graphics Editor : b3, 2025-01-01, 2025-02-01
        Vector Graphics runtime : b4, 2025-01-01, 2025-02-01
    section Minimal Viable Product (MVP)
        Intermediate Graphics : c1, 2025-02-01, 2025-03-01
        Accounts : c1, 2025-02-01, 2025-03-01
        Projects : c1, 2025-02-01, 2025-03-01
    section Alpha
        Alpha Testing and Fixes      : d1, 2025-03-01, 2025-03-07
    section Beta
        Beta Release and Feedback    : e1, 2025-03-07, 2025-04-01
    section 1.0 Release
        Live Graphics Editor         : c4, 2025-04-01, 2025-05-01
        Android Runtime Support      : f1, 2025-04-01, 2025-06-15
        Android Editor Support       : f2, 2025-04-01, 2025-06-15
        Physics-Based Animations     : f3, 2025-04-01, 2025-07-15