%% Combined UML Component Diagrams - Dependency Diagram and View Hierarchy
graph TD
    InertiaContainer[InertiaContainer] -.->|Child| InertiaDataModel[InertiaDataModel]
    InertiaContainer[InertiaContainer] -.->|Child| InertiaContext[InertiaContext]
    InertiaContext[InertiaContext]-.->|References|InertiaDataModel[InertiaDataModel]
    InertiaContainer[InertiaContainer] -.->|Child| Inertiaable[Inertiaable]
    Inertiaable[Inertiaable]-.->|References|InertiaContext[InertiaContext]
